id: P235363F4
initial_creation_type: input
source_metadata:
  Title: Two Vajrayāna Works
  Editor: Benoytosh Bhattacharyya
  Publisher: Oriental Institute
  Place of Publication: Baroda, India
  Year: '1929'
  Jñānasiddhi:
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: '2019'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:21:48.679561'
last_modified_at: '2022-03-08T17:21:48.679570'
